spring.application.name=fitness-monolith
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db
spring.datasource.username=root
spring.datasource.password=Harsh@9595

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true